spring:
  application:
    name: czas-na-wypad-backend
springdoc:
  api-docs:
    path: /api-docs
server:
  shutdown: graceful
rsa:
  private-key: classpath:certs/private_key.pem
  public-key: classpath:certs/public_key.pem
