spring:
  application:
    name: czas-na-wypad-backend
#  autoconfigure:
#    exclude:
#      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

rsa:
  private-key: classpath:certs/private_key.pem
  public-key: classpath:certs/public_key.pem
