spring:
  application:
    name: czas-na-wypad-backend
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
springdoc:
  api-docs:
    path: /api-docs