name: Build on Pull Request

on:
  pull_request:
    types: [ opened, reopened, synchronize]
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Compile and execute tests
        run: |
          mvn clean install
